version: '3.7'

networks:
    laravel:
        driver: bridge
volumes:
  tostons-db-data:

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
        volumes:
            - .:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        restart: always
        tty: true
        ports:
            - 3306:3306
        volumes:
            - tostons-db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=TostPassAdmin
            - MYSQL_DATABASE=tostons_web_db
            - MYSQL_USER=pabloC
            - MYSQL_PASSWORD=mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        expose:
            - 9000
        networks:
            - laravel
