version: '3.7'

networks:
    tostons:
        driver: bridge
volumes:
  tostons-db-data:

services:
    tostons_nginx:
        image: nginx:alpine
        container_name: tostons_nginx
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
        volumes:
            - .:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - tostons_php
            - tostons_mysql
        networks:
            - tostons

    tostons_mysql:
        image: mysql:8.0
        container_name: tostons_mysql
        restart: always
        tty: true
        ports:
            - 3306:3306
        volumes:
            - tostons-db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=TostPassAdmin
            - MYSQL_DATABASE=tostons_web_db
            - MYSQL_USER=pabloC
            - MYSQL_PASSWORD=mysql
        networks:
            - tostons

    tostons_php:
        build:
            context: .
            dockerfile: Dockerfile.php
        container_name: tostons_php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        expose:
            - 9000
        networks:
            - tostons
        depends_on:
         - tostons_mysql

    tostons_node:
        build:
            context: .
            dockerfile: Dockerfile.node
        container_name: tostons_node
        ports:
        - 3000:3000
        restart: unless-stopped
        working_dir: /var/www
        volumes:
        - ./:/var/www
        - /var/www/node_modules
        networks:
            - tostons
        depends_on:
         - tostons_php
